


export const courses = [
    // Level 400 1st semester courses
    {
        "id": 1,
        "title": "project management",
        "code": "",
        "category": "",
        "programme": "marketing",
        "level": 400,
        "semester": 1,
        "image": "",
        "description": " ",
        "slides": [
            {
                "id": 1,
                "url": "/current-slides/400/1",
                "title": "Introduction to PM",
                "author": "PETER THOMPSON",
                "published_day": 14,
                "published_month": "JAN",
                "published_year": 2024,
                "category": "Lecture 1",
                "filePath": "https://anansi-elearning-files.onrender.com/level100/timetable/Academic Timetable.pdf#toolbar=0",
            },
            {
                "id": 2,
                "url": "/current-slides/400/2",
                "title": "Advance PM",
                "author": "PETER THOMPSON",
                "published_day": 14,
                "published_month": "JAN",
                "published_year": 2024,
                "category": "Lecture 2",
                "filePath": "https://anansi-elearning-files.onrender.com/level100/timetable/Academic Timetable.pdf#toolbar=0",
            },
        ], // end of slides
        "pasco": [
            {
                "id": 1,
                "url": "/past-questions/400/1",
                "title": "2023/2024 Academic Timetable",
                "author": "PETER THOMPSON",
                "published_day": 14,
                "published_month": "JAN",
                "published_year": 2024,
                "category": "Semester 1",
                "filePath": "https://anansi-elearning-files.onrender.com/level100/timetable/Academic Timetable.pdf#toolbar=0",
            },
            {
                "id": 2,
                "url": "/past-questions/400/2",
                "title": "2023/2024 Academic Timetable",
                "author": "PETER THOMPSON",
                "published_day": 14,
                "published_month": "JAN",
                "published_year": 2024,
                "category": "Semester 1",
                "filePath": "https://anansi-elearning-files.onrender.com/level100/timetable/Academic Timetable.pdf#toolbar=0",
            },
        ], // end of pasco
    },
    // Level 400 1st semester courses
    {
        "id": 1,
        "title": "project management",
        "code": "",
        "category": "",
        "programme": "B.Com. Marketing",
        "level": 400,
        "semester": 1,
        "image": "",
        "description": " ",
        "slides": [
            {
                "id": 1,
                "url": "/current-slides/400/1",
                "title": "Introduction to PM",
                "author": "PETER THOMPSON",
                "published_day": 14,
                "published_month": "JAN",
                "published_year": 2024,
                "category": "Lecture 1",
                "filePath": "https://anansi-elearning-files.onrender.com/level100/timetable/Academic Timetable.pdf#toolbar=0",
            },
            {
                "id": 2,
                "url": "/current-slides/400/2",
                "title": "Advance PM",
                "author": "PETER THOMPSON",
                "published_day": 14,
                "published_month": "JAN",
                "published_year": 2024,
                "category": "Lecture 2",
                "filePath": "https://anansi-elearning-files.onrender.com/level100/timetable/Academic Timetable.pdf#toolbar=0",
            },
        ], // end of slides
        "pasco": [
            {
                "id": 1,
                "url": "/past-questions/400/1",
                "title": "2023/2024 Academic Timetable",
                "author": "PETER THOMPSON",
                "published_day": 14,
                "published_month": "JAN",
                "published_year": 2024,
                "category": "Semester 1",
                "filePath": "https://anansi-elearning-files.onrender.com/level100/timetable/Academic Timetable.pdf#toolbar=0",
            },
            {
                "id": 2,
                "url": "/past-questions/400/2",
                "title": "2023/2024 Academic Timetable",
                "author": "PETER THOMPSON",
                "published_day": 14,
                "published_month": "JAN",
                "published_year": 2024,
                "category": "Semester 1",
                "filePath": "https://anansi-elearning-files.onrender.com/level100/timetable/Academic Timetable.pdf#toolbar=0",
            },
        ], // end of pasco
    },
    // Level 400 1st semester courses
    {
        "id": 1,
        "title": "project management",
        "code": "",
        "category": "",
        "programme": "B.Com. Marketing",
        "level": 400,
        "semester": 1,
        "image": "",
        "description": " ",
        "slides": [
            {
                "id": 1,
                "url": "/current-slides/400/1",
                "title": "Introduction to PM",
                "author": "PETER THOMPSON",
                "published_day": 14,
                "published_month": "JAN",
                "published_year": 2024,
                "category": "Lecture 1",
                "filePath": "https://anansi-elearning-files.onrender.com/level100/timetable/Academic Timetable.pdf#toolbar=0",
            },
            {
                "id": 2,
                "url": "/current-slides/400/2",
                "title": "Advance PM",
                "author": "PETER THOMPSON",
                "published_day": 14,
                "published_month": "JAN",
                "published_year": 2024,
                "category": "Lecture 2",
                "filePath": "https://anansi-elearning-files.onrender.com/level100/timetable/Academic Timetable.pdf#toolbar=0",
            },
        ], // end of slides
        "pasco": [
            {
                "id": 1,
                "url": "/past-questions/400/1",
                "title": "2023/2024 Academic Timetable",
                "author": "PETER THOMPSON",
                "published_day": 14,
                "published_month": "JAN",
                "published_year": 2024,
                "category": "Semester 1",
                "filePath": "https://anansi-elearning-files.onrender.com/level100/timetable/Academic Timetable.pdf#toolbar=0",
            },
            {
                "id": 2,
                "url": "/past-questions/400/2",
                "title": "2023/2024 Academic Timetable",
                "author": "PETER THOMPSON",
                "published_day": 14,
                "published_month": "JAN",
                "published_year": 2024,
                "category": "Semester 1",
                "filePath": "https://anansi-elearning-files.onrender.com/level100/timetable/Academic Timetable.pdf#toolbar=0",
            },
        ], // end of pasco
    },
    // Level 100 1st semester courses
    {
        "id": 101,
        "title": "Communicative Skills",
        "code": "",
        "category": "",
        "programme": "general course",
        "level": 100,
        "semester": 1,
        "image": "",
        "description": " ",
        "slides": [
            {
                "id": 1,
                "url": "/current-slides/100/1",
                "title": "Introduction to Communicative Skills",
                "author": "DIANA ASAMOAH",
                "published_day": 17,
                "published_month": "FEB",
                "published_year": 2024,
                "category": "Lecture 1",
                "filePath": "https://anansi-elearning-files.onrender.com/level100/timetable/Academic Timetable.pdf#toolbar=0",
            },
            {
                "id": 2,
                "url": "/current-slides/100/2",
                "title": "Advance PM",
                "author": "DIANA ASAMOAH",
                "published_day": 17,
                "published_month": "FEB",
                "published_year": 2024,
                "category": "Lecture 2",
                "filePath": "https://anansi-elearning-files.onrender.com/level100/timetable/Academic Timetable.pdf#toolbar=0",
            },
        ], // end of slides
        "pasco": [
            {
                "id": 1,
                "url": "/past-questions/100/1",
                "title": "Communicative Skills Pasco #1",
                "author": "GYANDY GABRIEL",
                "published_day": 28,
                "published_month": "MAY",
                "published_year": 2022,
                "category": "Semester 1",
                "filePath": "https://anansi-elearning-files.onrender.com/level100/timetable/Academic Timetable.pdf#toolbar=0",
            },
            {
                "id": 2,
                "url": "/past-questions/100/2",
                "title": "Communicative Skills Pasco #2",
                "author": "GYANDY GABRIEL",
                "published_day": 28,
                "published_month": "MAY",
                "published_year": 2022,
                "category": "Semester 1",
                "filePath": "https://anansi-elearning-files.onrender.com/level100/timetable/Academic Timetable.pdf#toolbar=0",
            },
        ], // end of pasco
    },
    // Level 100 1st semester courses
    {
        "id": 102,
        "title": "Information Literacy Skills",
        "code": "",
        "category": "",
        "programme": "general course",
        "level": 100,
        "semester": 1,
        "image": "",
        "description": " ",
        "slides": [
            {
                "id": 1,
                "url": "/current-slides/100/1",
                "title": "Introduction to Info Lit Skills",
                "author": "DIANA ASAMOAH",
                "published_day": 17,
                "published_month": "FEB",
                "published_year": 2024,
                "category": "Lecture 1",
                "filePath": "https://anansi-elearning-files.onrender.com/level100/timetable/Academic Timetable.pdf#toolbar=0",
            },
            {
                "id": 2,
                "url": "/current-slides/100/2",
                "title": "Info Lit 2",
                "author": "DIANA ASAMOAH",
                "published_day": 17,
                "published_month": "FEB",
                "published_year": 2024,
                "category": "Lecture 2",
                "filePath": "https://anansi-elearning-files.onrender.com/level100/timetable/Academic Timetable.pdf#toolbar=0",
            },
        ], // end of slides
        "pasco": [
            {
                "id": 1,
                "url": "/past-questions/100/1",
                "title": "Info Lit Pasco #1",
                "author": "GYANDY GABRIEL",
                "published_day": 28,
                "published_month": "MAY",
                "published_year": 2022,
                "category": "Semester 1",
                "filePath": "https://anansi-elearning-files.onrender.com/level100/timetable/Academic Timetable.pdf#toolbar=0",
            },
            {
                "id": 2,
                "url": "/past-questions/100/1",
                "title": "Info Lit Pasco #2",
                "author": "GYANDY GABRIEL",
                "published_day": 28,
                "published_month": "MAY",
                "published_year": 2022,
                "category": "Semester 1",
                "filePath": "https://anansi-elearning-files.onrender.com/level100/timetable/Academic Timetable.pdf#toolbar=0",
            },
        ], // end of pasco
    },

]