


export const courses = [
    // Level 400 1st semester courses
    {
        "id": 1,
        "title": "project management",
        "code": "",
        "category": "",
        "programme": "marketing",
        "level": 400,
        "semester": 1,
        "image": "",
        "description": " ",
        "slides": [
            {
                "id": 1,
                "url": "/current-slides/400/pm401/slides/1",
                "title": "Introduction to PM",
                "author": "PETER THOMPSON",
                "published_day": 14,
                "published_month": "JAN",
                "published_year": 2024,
                "category": "Lecture 1",
                "filePath": "https://anansi-elearning-files-400.onrender.com/level400/general/projectmanagement/slides/Lecture 01-Introduction to PM.pdf#toolbar=0",
            },
            {
                "id": 2,
                "url": "/current-slides/400/pm401/slides/2",
                "title": "Organizational Strategy and Projects",
                "author": "PETER THOMPSON",
                "published_day": 14,
                "published_month": "JAN",
                "published_year": 2024,
                "category": "Lecture 2",
                "filePath": "https://anansi-elearning-files-400.onrender.com/level400/general/projectmanagement/slides/Lecture 02-Organizational Strategy and Projects.pdf#toolbar=0",
            },
            {
                "id": 3,
                "url": "/current-slides/400/pm401/slides/3",
                "title": "Project Selection Portfolio Mgt",
                "author": "PETER THOMPSON",
                "published_day": 14,
                "published_month": "JAN",
                "published_year": 2024,
                "category": "Lecture 3",
                "filePath": "https://anansi-elearning-files-400.onrender.com/level400/general/projectmanagement/slides/Lecture 03-Project Selection _ Portfolio Mgt.pdf#toolbar=0",
            },
            {
                "id": 4,
                "url": "/current-slides/400/pm401/slides/4",
                "title": "Leadership",
                "author": "PETER THOMPSON",
                "published_day": 14,
                "published_month": "JAN",
                "published_year": 2024,
                "category": "Lecture 4",
                "filePath": "https://anansi-elearning-files-400.onrender.com/level400/general/projectmanagement/slides/Lecture 04-Leadership _ Project Management.pdf#toolbar=0",
            },
        ], // end of slides
        "pasco": [
            {
                "id": 1,
                "url": "/past-questions/400/pm401/pasco/1",
                "title": "Project Management",
                "author": "PETER THOMPSON",
                "published_day": 14,
                "published_month": "JAN",
                "published_year": 2024,
                "category": "Semester 1",
                "filePath": "https://anansi-elearning-files-400.onrender.com/level400/general/projectmanagement/pasco/PM ASS FULL.pdf#toolbar=0",
            },
            
        ], // end of pasco
    },
    // Level 400 1st semester courses
    {
        "id": 2,
        "title": "enterpreneurship",
        "code": "",
        "category": "",
        "programme": "",
        "level": 400,
        "semester": 1,
        "image": "",
        "description": " ",
        "slides": [
            {
                "id": 1,
                "url": "/current-slides/400/ent401/slides/1",
                "title": "Personality",
                "author": "PETER THOMPSON",
                "published_day": 14,
                "published_month": "JAN",
                "published_year": 2024,
                "category": "Lecture 1",
                "filePath": "https://anansi-elearning-files-400.onrender.com/level400/general/enterpreneurship/slides/2. Personality.pdf#toolbar=0",
            },
            {
                "id": 2,
                "url": "/current-slides/400/ent401/slides/2",
                "title": "Business Concept",
                "author": "PETER THOMPSON",
                "published_day": 14,
                "published_month": "JAN",
                "published_year": 2024,
                "category": "Lecture 2",
                "filePath": "https://anansi-elearning-files-400.onrender.com/level400/general/enterpreneurship/slides/5. Business Concept.pdf#toolbar=0",
            },
            {
                "id": 3,
                "url": "/current-slides/400/ent401/slides/3",
                "title": "Team formation",
                "author": "PETER THOMPSON",
                "published_day": 14,
                "published_month": "JAN",
                "published_year": 2024,
                "category": "Lecture 3",
                "filePath": "https://anansi-elearning-files-400.onrender.com/level400/general/enterpreneurship/slides/7. Team formation.pdf#toolbar=0",
            },
            {
                "id": 4,
                "url": "/current-slides/400/ent401/slides/4",
                "title": "Entrepreneurial financing",
                "author": "PETER THOMPSON",
                "published_day": 14,
                "published_month": "JAN",
                "published_year": 2024,
                "category": "Lecture 4",
                "filePath": "https://anansi-elearning-files-400.onrender.com/level400/general/enterpreneurship/slides/9. Entrepreneurial financing.pdf#toolbar=0",
            },
            // {
            //     "id": 5,
            //     "url": "/current-slides/400/5",
            //     "title": "Ethics",
            //     "author": "PETER THOMPSON",
            //     "published_day": 14,
            //     "published_month": "JAN",
            //     "published_year": 2024,
            //     "category": "Lecture 5",
            //     "filePath": "https://anansi-elearning-files-400.onrender.com/level400/general/enterpreneurship/slides/Lecture 10 Ethics.pdf#toolbar=0",
            // },
        ], // end of slides
        "pasco": [
            {
                "id": 1,
                "url": "/past-questions/400/ent401/pasco/1",
                "title": "B-PLAN NEW",
                "author": "PETER THOMPSON",
                "published_day": 14,
                "published_month": "JAN",
                "published_year": 2024,
                "category": "Semester 1",
                "filePath": "https://anansi-elearning-files-400.onrender.com/level400/general/enterpreneurship/pasco/B-PLAN NEW.pdf#toolbar=0",
            },
            {
                "id": 2,
                "url": "/past-questions/400/ent401/pasco/2",
                "title": "Coffee Bar buz concept -TeamCastyScholars",
                "author": "PETER THOMPSON",
                "published_day": 14,
                "published_month": "JAN",
                "published_year": 2024,
                "category": "Semester 1",
                "filePath": "https://anansi-elearning-files-400.onrender.com/level400/general/enterpreneurship/pasco/Coffee Bar buz concept -TeamCastyScholars.pdf#toolbar=0",
            },
        ], // end of pasco
    },
    // Level 300 1st semester courses
    {
        "id": 1,
        "title": "operations management",
        "code": "",
        "category": "",
        "programme": "",
        "level": 300,
        "semester": 1,
        "image": "",
        "description": " ",
        "slides": [
            {
                "id": 1,
                "url": "/current-slides/300/opm301/slides/1",
                "title": "Overview of Production and Operations Management",
                "author": "PETER THOMPSON",
                "published_day": 14,
                "published_month": "JAN",
                "published_year": 2024,
                "category": "Lecture 1",
                "filePath": "https://anansi-elearning-files-300.onrender.com/level300/general/operationsmanagement/slides/chapter 1 Overview of Production and Operations Management.pdf#toolbar=0",
            },
            {
                "id": 2,
                "url": "/current-slides/300/opm301/slides/2",
                "title": "Information Technology and Operations Management",
                "author": "PETER THOMPSON",
                "published_day": 14,
                "published_month": "JAN",
                "published_year": 2024,
                "category": "Lecture 2",
                "filePath": "https://anansi-elearning-files-300.onrender.com/level300/general/operationsmanagement/slides/chapter 2 Information Technology and Operations Management.pdf#toolbar=0",
            },
            {
                "id": 3,
                "url": "/current-slides/300/opm301/slides/3",
                "title": "The Concept of Globalization",
                "author": "PETER THOMPSON",
                "published_day": 14,
                "published_month": "JAN",
                "published_year": 2024,
                "category": "Lecture 3",
                "filePath": "https://anansi-elearning-files-300.onrender.com/level300/general/operationsmanagement/slides/chapter 3 The Concept of Globalization.pdf#toolbar=0",
            },
            {
                "id": 4,
                "url": "/current-slides/300/opm301/slides/4",
                "title": "Developing Strategy, Missions And Competitiveness",
                "author": "PETER THOMPSON",
                "published_day": 14,
                "published_month": "JAN",
                "published_year": 2024,
                "category": "Lecture 4",
                "filePath": "https://anansi-elearning-files-300.onrender.com/level300/general/operationsmanagement/slides/chapter 4 Developing Strategy, Missions And Competitiveness.pdf#toolbar=0",
            },
            // {
            //     "id": 5,
            //     "url": "/current-slides/300/opm301/slides/5",
            //     "title": "Process Management or Measurement and Analysis",
            //     "author": "PETER THOMPSON",
            //     "published_day": 14,
            //     "published_month": "JAN",
            //     "published_year": 2024,
            //     "category": "Lecture 5",
            //     "filePath": "https://anansi-elearning-files-300.onrender.com/level300/general/operationsmanagement/slides/chapter 5 Process Management or Measurement and Analysis.pdf#toolbar=0",
            // },
        ], // end of slides
        "pasco": [
            {
                "id": 1,
                "url": "/past-questions/300/opm301/pasco/1",
                "title": "OPERATIONS MANAGEMENT 1",
                "author": "PETER THOMPSON",
                "published_day": 14,
                "published_month": "JAN",
                "published_year": 2024,
                "category": "Semester 1",
                "filePath": "https://anansi-elearning-files-300.onrender.com/level300/general/operationsmanagement/pasco/OPERATIONS MANAGEMENT 1.pdf#toolbar=0",
            },
            {
                "id": 2,
                "url": "/past-questions/300/opm301/pasco/2",
                "title": "OPERATIONS MANAGEMENT 2",
                "author": "PETER THOMPSON",
                "published_day": 14,
                "published_month": "JAN",
                "published_year": 2024,
                "category": "Semester 1",
                "filePath": "https://anansi-elearning-files-300.onrender.com/level300/general/operationsmanagement/pasco/OPERATIONS MANAGEMENT 2.pdf#toolbar=0",
            },
            {
                "id": 3,
                "url": "/past-questions/300/opm301/pasco/3",
                "title": "OPERATIONS MANAGEMENT QUESTIONS",
                "author": "PETER THOMPSON",
                "published_day": 14,
                "published_month": "JAN",
                "published_year": 2024,
                "category": "Semester 1",
                "filePath": "https://anansi-elearning-files-300.onrender.com/level300/general/operationsmanagement/pasco/OPERATIONS MANAGEMENT QUESTIONS.pdf#toolbar=0",
            },
            {
                "id": 4,
                "url": "/past-questions/300/opm301/pasco/4",
                "title": "OPERATIONS MANAGEMENT QUIZ",
                "author": "PETER THOMPSON",
                "published_day": 14,
                "published_month": "JAN",
                "published_year": 2024,
                "category": "Semester 1",
                "filePath": "https://anansi-elearning-files-300.onrender.com/level300/general/operationsmanagement/pasco/OPERATIONS MANAGEMENT QUIZ.pdf#toolbar=0",
            },
        ], // end of pasco
    },
    // Level 200 1st semester courses
    {
        "id": 1,
        "title": "human resource management",
        "code": "",
        "category": "",
        "programme": "",
        "level": 200,
        "semester": 1,
        "image": "",
        "description": " ",
        "slides": [
            {
                "id": 1,
                "url": "/current-slides/200/hrm201/slides/1",
                "title": "Learning Theories and Organisations",
                "author": "PETER THOMPSON",
                "published_day": 14,
                "published_month": "JAN",
                "published_year": 2024,
                "category": "Lecture 7",
                "filePath": "https://anansi-elearning-files-200.onrender.com/level200/hrm/slides/HRM_Week_Seven_Learning_Theories_and_Organisations.pdf#toolbar=0",
            },
            
        ], // end of slides
        "pasco": [
            {
                "id": 1,
                "url": "/past-questions/200/hrm201/pasco/1",
                "title": "HRM EXAM PAST QUESTIONS",
                "author": "PETER THOMPSON",
                "published_day": 14,
                "published_month": "JAN",
                "published_year": 2024,
                "category": "Semester 1",
                "filePath": "https://anansi-elearning-files-200.onrender.com/level200/hrm/pasco/HRM EXAM PAST QUESTIONS.pdf#toolbar=0",
            },
            {
                "id": 2,
                "url": "/past-questions/200/hrm201/pasco/2",
                "title": "HRM PAST QUESTIONS AND ANSWERS",
                "author": "PETER THOMPSON",
                "published_day": 14,
                "published_month": "JAN",
                "published_year": 2024,
                "category": "Semester 1",
                "filePath": "https://anansi-elearning-files-200.onrender.com/level200/hrm/pasco/HRM PAST QUESTIONS AND ANSWERS.pdf#toolbar=0",
            },
            {
                "id": 3,
                "url": "/past-questions/200/hrm201/pasco/3",
                "title": "HRM past question",
                "author": "PETER THOMPSON",
                "published_day": 14,
                "published_month": "JAN",
                "published_year": 2024,
                "category": "Semester 1",
                "filePath": "https://anansi-elearning-files-200.onrender.com/level200/hrm/pasco/HRM past question.pdf#toolbar=0",
            },
            {
                "id": 4,
                "url": "/past-questions/200/hrm201/pasco/4",
                "title": "HRM__.Passco Daakyehene",
                "author": "Daakyehene",
                "published_day": 14,
                "published_month": "JAN",
                "published_year": 2024,
                "category": "Semester 1",
                "filePath": "https://anansi-elearning-files-200.onrender.com/level200/hrm/pasco/HRM__.Passco Daakyehene.pdf#toolbar=0",
            },
            // {
            //     "id": 5,
            //     "url": "/past-questions/200/hrm201/pasco/5",
            //     "title": "HRM",
            //     "author": "Daakyehene",
            //     "published_day": 14,
            //     "published_month": "JAN",
            //     "published_year": 2024,
            //     "category": "Semester 1",
            //     "filePath": "https://anansi-elearning-files-200.onrender.com/level200/hrm/pasco/HRM.pdf#toolbar=0",
            // },
        ], // end of pasco
    },

    // Level 100 1st semester courses
    {
        "id": 1,
        "title": "Communicative Skills",
        "code": "",
        "category": "",
        "programme": "general course",
        "level": 100,
        "semester": 1,
        "image": "",
        "description": " ",
        "slides": [
            {
                "id": 1,
                "url": "/current-slides/100/cms101/slides/1",
                "title": "coordination and subordination",
                "author": "DIANA ASAMOAH",
                "published_day": 17,
                "published_month": "FEB",
                "published_year": 2024,
                "category": "Lecture 1",
                "filePath": "https://anansi-elearning-files.onrender.com/level100/general/comskills/slides/coordinationandsubordination.pdf#toolbar=0",
            },
            
        ], // end of slides
        "pasco": [
            {
                "id": 1,
                "url": "/past-questions/100/cms101/pasco/1",
                "title": "Communicative Skills Pasco #1",
                "author": "UCCABS",
                "published_day": 28,
                "published_month": "MAY",
                "published_year": 2022,
                "category": "Semester 1",
                "filePath": "https://anansi-elearning-files.onrender.com/level100/general/comskills/pasco/UCCABS-COM-SKILLS-PASCO.pdf#toolbar=0",
            },
            {
                "id": 2,
                "url": "/past-questions/100/cms101/pasco/2",
                "title": "Communicative Skills Pasco #2",
                "author": "UCCABS",
                "published_day": 28,
                "published_month": "MAY",
                "published_year": 2022,
                "category": "Semester 1",
                "filePath": "https://anansi-elearning-files.onrender.com/level100/general/comskills/pasco/com-skills-pasco.pdf#toolbar=0",
            },
        ], // end of pasco
    },
    // Level 100 1st semester courses
    {
        "id": 2,
        "title": "Information Literacy Skills",
        "code": "",
        "category": "",
        "programme": "general course",
        "level": 100,
        "semester": 1,
        "image": "",
        "description": " ",
        "slides": [
            {
                "id": 1,
                "url": "/current-slides/100/its101/slides/1",
                "title": "Introduction to Info Lit Skills",
                "author": "DIANA ASAMOAH",
                "published_day": 17,
                "published_month": "FEB",
                "published_year": 2024,
                "category": "Lecture 1",
                "filePath": "https://anansi-elearning-files.onrender.com/level100/general/infolit/slides/Session 1 information literacy -Compatibility Mode-.pdf#toolbar=0",
            },
            {
                "id": 2,
                "url": "/current-slides/100/its101/slides/2",
                "title": "Libraries",
                "author": "DIANA ASAMOAH",
                "published_day": 17,
                "published_month": "FEB",
                "published_year": 2024,
                "category": "Lecture 2",
                "filePath": "https://anansi-elearning-files.onrender.com/level100/general/infolit/slides/Session 2 - Libraries -Compatibility Mode-.pdf#toolbar=0",
            },
        ], // end of slides
        "pasco": [
            {
                "id": 1,
                "url": "/past-questions/100/its101/pasco/1",
                "title": "TRIAL QUESTION 1",
                "author": "GYANDY GABRIEL",
                "published_day": 28,
                "published_month": "MAY",
                "published_year": 2022,
                "category": "Semester 1",
                "filePath": "https://anansi-elearning-files.onrender.com/level100/general/infolit/pasco/TRIAL QUESTION 1.pdf#toolbar=0",
            },
            {
                "id": 2,
                "url": "/past-questions/100/its101/pasco/2",
                "title": "TRIAL QUESTION 2",
                "author": "GYANDY GABRIEL",
                "published_day": 28,
                "published_month": "MAY",
                "published_year": 2022,
                "category": "Semester 1",
                "filePath": "https://anansi-elearning-files.onrender.com/level100/general/infolit/pasco/TRIAL QUESTION 2.pdf#toolbar=0",
            },
        ], // end of pasco
    },

]