

export const users = [
    {
        "id": 1,
        "role": "student",
        "username": "ps/csc/20/0012",
        "first_name": "Mesh",
        "last_name": "Com",
        "other_name": "Obvious",
        "email": "mesh@gmail.com",
        "password": "123456",
        "level": 3,
        "programme": "B.Sc. Computer Science",
        "courses": [],
        "date_created": "21/02/2024",
        "data_updated": "27/02/2024",
    },
//users array index 1
    {
        "id": 2,
        "role": "student",
        "username": "sb/mkn/20/0041",
        "first_name": "Kelvin",
        "last_name": "Yeboah",
        "other_name": "Mantse",
        "email": "kelly@gmail.com",
        "password": "kelly123",
        "level": 400,
        "programme": "B.Com. Marketing",
        "courses": [
            {
                "id": 1,
                "title": "Project Management",
                "code": "PM 401",
                "semester": "1st",
                "image": "",
                "description": "",
                "url": "",
                "pascoURL": "/dashboard/fourth/bcom-marketing/past-questions/project-management-pasco",
                "slidesURL": "/dashboard/fourth/bcom-marketing/current-slides/project-management-slides",
                "dateUpdated": [12, "MAR", 2024],
                "uploadedBy": "",
            },
            {
                "id": 2,
                "title": "Enterpreneurship",
                "code": "ENT 401",
                "semester": "1st",
                "image": "",
                "description": "",
                "url": "",
                "pascoURL": "/dashboard/fourth/bcom-marketing/past-questions/enterpreneurship-pasco",
                "pascoFiles": [],
                "slidesURL": "/dashboard/fourth/bcom-marketing/current-slides/enterpreneurship-slides",
                "dateUpdated": [12, "MAR", 2024],
                "uploadedBy": "",
            },
            {
                "id": 3,
                "title": "Design Thinking and Innovation",
                "code": "DTI 401",
                "semester": "1st",
                "image": "",
                "description": "",
                "url": "",
                "pascoURL": "/dashboard/fourth/bcom-marketing/past-questions/design-thinking-pasco",
                "slidesURL": "/dashboard/fourth/bcom-marketing/current-slides/design-thinking-slides",
                "dateUpdated": [12, "MAR", 2024],
                "uploadedBy": "",
            },
            {
                "id": 4,
                "title": "Financial Management",
                "code": "FIN 401",
                "semester": "1st",
                "image": "",
                "description": "",
                "url": "",
                "pascoURL": "/dashboard/fourth/bcom-marketing/past-questions/financial-management-pasco",
                "slidesURL": "/dashboard/fourth/bcom-marketing/current-slides/financial-management-slides",
                "dateUpdated": [12, "MAR", 2024],
                "uploadedBy": "",
            },
            {
                "id": 5,
                "title": "Marketing Research",
                "code": "MKN 401",
                "semester": "1st",
                "image": "",
                "description": "",
                "url": "",
                "pascoURL": "/dashboard/fourth/bcom-marketing/past-questions/marketing-research-pasco",
                "slidesURL": "/dashboard/fourth/bcom-marketing/current-slides/marketing-research-slides",
                "dateUpdated": [12, "MAR", 2024],
                "uploadedBy": "",
            },
            {
                "id": 6,
                "title": "Self Management",
                "code": "MNG 401",
                "semester": "1st",
                "image": "",
                "description": "",
                "url": "",
                "pascoURL": "/dashboard/fourth/bcom-marketing/past-questions/self-management-pasco",
                "slidesURL": "/dashboard/fourth/bcom-marketing/current-slides/self-management-slides",
                "dateUpdated": [12, "MAR", 2024],
                "uploadedBy": "",
            },
        ],
        "date_created": "21/02/2024",
        "data_updated": "27/02/2024",
    },
//users array index 2
    {
        "id": 3,
        "role": "student",
        "username": "sb/pcm/20/0022",
        "first_name": "Felicia",
        "last_name": "Adjei",
        "other_name": "",
        "email": "felicia@gmail.com",
        "password": "felicia123",
        "level": 400,
        "programme": "B.Com. Procurement",
        "courses": [
            {
                "id": 1,
                "title": "Project Management",
                "code": "PM 401",
                "semester": "1st",
                "image": "",
                "description": "",
                "url": "",
                "pascoURL": "/dashboard/fourth/bcom-procurement/past-questions/project-management-pasco",
                "slidesURL": "/dashboard/fourth/bcom-procurement/current-slides/project-management-slides",
                "dateUpdated": [12, "MAR", 2024],
                "uploadedBy": "",
            },
            {
                "id": 2,
                "title": "Enterpreneurship",
                "code": "ENT 401",
                "semester": "1st",
                "image": "",
                "description": "",
                "url": "",
                "pascoURL": "/dashboard/fourth/bcom-procurement/past-questions/enterpreneurship-pasco",
                "slidesURL": "/dashboard/fourth/bcom-procurement/current-slides/enterpreneurship-slides",
                "dateUpdated": [12, "MAR", 2024],
                "uploadedBy": "",
            },
            {
                "id": 3,
                "title": "Design Thinking and Innovation",
                "code": "DTI 401",
                "semester": "1st",
                "image": "",
                "description": "",
                "url": "",
                "pascoURL": "/dashboard/fourth/bcom-procurement/past-questions/design-thinking-pasco",
                "slidesURL": "/dashboard/fourth/bcom-procurement/current-slides/design-thinking-slides",
                "dateUpdated": [12, "MAR", 2024],
                "uploadedBy": "",
            },
            {
                "id": 4,
                "title": "Risk Management",
                "code": "RM 401",
                "semester": "1st",
                "image": "",
                "description": "",
                "url": "",
                "pascoURL": "/dashboard/fourth/bcom-procurement/past-questions/risk-management-pasco",
                "slidesURL": "/dashboard/fourth/bcom-procurement/current-slides/risk-management-slides",
                "dateUpdated": [12, "MAR", 2024],
                "uploadedBy": "",
            },
            {
                "id": 5,
                "title": "Sustainable Procurement",
                "code": "RMT 301",
                "semester": "1st",
                "image": "",
                "description": "",
                "url": "",
                "pascoURL": "/dashboard/fourth/bcom-procurement/past-questions/sustainable-procurement-pasco",
                "slidesURL": "/dashboard/fourth/bcom-procurement/current-slides/sustainable-procurement-slides",
                "dateUpdated": [12, "MAR", 2024],
                "uploadedBy": "",
            },
            {
                "id": 6,
                "title": "LEAN",
                "code": "LEAN 401",
                "semester": "1st",
                "image": "",
                "description": "",
                "url": "",
                "pascoURL": "/dashboard/fourth/bcom-procurement/past-questions/lean-pasco",
                "slidesURL": "/dashboard/fourth/bcom-procurement/current-slides/lean-slides",
                "dateUpdated": [12, "MAR", 2024],
                "uploadedBy": "",
            },
        ],
        "date_created": "21/02/2024",
        "data_updated": "27/02/2024",
    },
//users array index 3
    {
        "id": 4,
        "role": "student",
        "username": "sb/mkn/20/0048",
        "first_name": "Lerroy",
        "last_name": "Bruce",
        "other_name": "Kojo",
        "email": "lerroy@gmail.com",
        "password": "lerroy123",
        "level": 300,
        "programme": "B.Com. Marketing",
        "courses": [
            {
                "id": 1,
                "title": "Operations Management",
                "code": "OPM 301",
                "semester": "1st",
                "image": "",
                "description": "",
                "url": "",
                "pascoURL": "",
                "slidesURL": "",
                "dateUpdated": [12, "MAR", 2024],
                "uploadedBy": "",
            },
            {
                "id": 2,
                "title": "Managerial Economics",
                "code": "ECO 301",
                "semester": "1st",
                "image": "",
                "description": "",
                "url": "",
                "pascoURL": "",
                "slidesURL": "",
                "dateUpdated": [12, "MAR", 2024],
                "uploadedBy": "",
            },
            {
                "id": 3,
                "title": "Cost Accounting",
                "code": "ACC 101",
                "semester": "1st",
                "image": "",
                "description": "",
                "url": "",
                "pascoURL": "",
                "slidesURL": "",
                "dateUpdated": [12, "MAR", 2024],
                "uploadedBy": "",
            },
            {
                "id": 4,
                "title": "Business Statistics",
                "code": "STAT 301",
                "semester": "1st",
                "image": "",
                "description": "",
                "url": "",
                "pascoURL": "",
                "slidesURL": "",
                "dateUpdated": [12, "MAR", 2024],
                "uploadedBy": "",
            },
            {
                "id": 5,
                "title": "Research Methods",
                "code": "RMT 301",
                "semester": "1st",
                "image": "",
                "description": "",
                "url": "",
                "pascoURL": "",
                "slidesURL": "",
                "dateUpdated": [12, "MAR", 2024],
                "uploadedBy": "",
            },
        ],
        "date_created": "21/02/2024",
        "data_updated": "27/02/2024",
    },
//users array index 4
    {
        "id": 5,
        "role": "student",
        "username": "sb/pcm/20/0133",
        "first_name": "Augustine",
        "last_name": "Agyapong",
        "other_name": "",
        "email": "augustine@gmail.com",
        "password": "augustine123",
        "level": 200,
        "programme": "B.Com. Procurement",
        "courses": [
            {
                "id": 1,
                "title": "Business Law",
                "code": "BUS 201",
                "semester": "1st",
                "image": "",
                "description": "",
                "url": "",
                "pascoURL": "/dashboard/second/bcom-procurement/past-questions/business-law-pasco",
                "slidesURL": "/dashboard/second/bcom-procurement/current-slides/business-law-slides",
                "dateUpdated": [12, "MAR", 2024],
                "uploadedBy": "",
            },
            {
                "id": 2,
                "title": "Quantitative Methods",
                "code": "QNT 201",
                "semester": "1st",
                "image": "",
                "description": "",
                "url": "",
                "pascoURL": "/dashboard/second/bcom-procurement/past-questions/quantitative-methods-pasco",
                "slidesURL": "/dashboard/second/bcom-procurement/current-slides/quantitative-methods-slides",
                "dateUpdated": [12, "MAR", 2024],
                "uploadedBy": "",
            },
            {
                "id": 3,
                "title": "Critical Thinking",
                "code": "CRT 201",
                "semester": "1st",
                "image": "",
                "description": "",
                "url": "",
                "pascoURL": "/dashboard/second/bcom-procurement/past-questions/critical-thinking-pasco",
                "slidesURL": "/dashboard/second/bcom-procurement/current-slides/critical-thinking-slides",
                "dateUpdated": [12, "MAR", 2024],
                "uploadedBy": "",
            },
        ],
        "date_created": "21/02/2024",
        "data_updated": "27/02/2024",
    },
//users array index 5
    {
        "id": 6,
        "role": "student",
        "username": "sb/pcm/20/0179",
        "first_name": "Andoh",
        "last_name": "Quansah",
        "other_name": "Kofi",
        "email": "andoh@gmail.com",
        "password": "andoh123",
        "level": 100,
        "programme": "B.Com. Procurement",
        "courses": [
            {
                "id": 1,
                "title": "Communication Skills",
                "code": "COM 101",
                "semester": "1st",
                "image": "",
                "description": "",
                "url": "",
                "pascoURL": "",
                "slidesURL": "",
                "dateUpdated": [12, "MAR", 2024],
                "uploadedBy": "",
            },
            {
                "id": 2,
                "title": "Infomation Literacy Skills",
                "code": "ITS 101",
                "semester": "1st",
                "image": "",
                "description": "",
                "url": "",
                "pascoURL": "",
                "slidesURL": "",
                "dateUpdated": [12, "MAR", 2024],
                "uploadedBy": "",
            },
            {
                "id": 3,
                "title": "Financial Accounting",
                "code": "FIN 101",
                "semester": "1st",
                "image": "",
                "description": "",
                "url": "",
                "pascoURL": "",
                "slidesURL": "",
                "dateUpdated": [12, "MAR", 2024],
                "uploadedBy": "",
            },
            {
                "id": 4,
                "title": "Micro Economics",
                "code": "ECO 101",
                "semester": "1st",
                "image": "",
                "description": "",
                "url": "",
                "pascoURL": "",
                "slidesURL": "",
                "dateUpdated": [12, "MAR", 2024],
                "uploadedBy": "",
            },
        ],
        "date_created": "21/02/2024",
        "data_updated": "27/02/2024",
    },
//users array index 6
{
    "id": 7,
    "role": "student",
    "username": "sb/pcm/20/0027",
    "first_name": "Martina",
    "last_name": "",
    "other_name": "",
    "email": "martina@gmail.com",
    "password": "martina123",
    "level": 100,
    "programme": "B.Com. Finance",
    "courses": [
        {
            "id": 1,
            "title": "Communication Skills",
            "code": "COM 101",
            "semester": "1st",
            "image": "",
            "description": "",
            "url": "",
            "pascoURL": "",
            "slidesURL": "",
            "dateUpdated": [12, "MAR", 2024],
            "uploadedBy": "",
        },
        {
            "id": 2,
            "title": "Infomation Literacy Skills",
            "code": "ITS 101",
            "semester": "1st",
            "image": "",
            "description": "",
            "url": "",
            "pascoURL": "",
            "slidesURL": "",
            "dateUpdated": [12, "MAR", 2024],
            "uploadedBy": "",
        },
        {
            "id": 3,
            "title": "Financial Accounting",
            "code": "FIN 101",
            "semester": "1st",
            "image": "",
            "description": "",
            "url": "",
            "pascoURL": "",
            "slidesURL": "",
            "dateUpdated": [12, "MAR", 2024],
            "uploadedBy": "",
        },
        {
            "id": 4,
            "title": "Micro Economics",
            "code": "ECO 101",
            "semester": "1st",
            "image": "",
            "description": "",
            "url": "",
            "pascoURL": "",
            "slidesURL": "",
            "dateUpdated": [12, "MAR", 2024],
            "uploadedBy": "",
        },
    ],
    "date_created": "21/02/2024",
    "data_updated": "27/02/2024",
},
]